### ISSUE TITLE
Serverless offline not working

### ISSUE THREAD

**Issue by Paul4912** [AnomalyInnovations/serverless-stack-demo-ext-api#9]
Hi, 
When i invoke the function locally with something like this, it works.
serverless invoke local -f get --path events/get-event.json 

However when i try to do serverless offline it seems to screw up on the dynamoDB part and returns back a 500, { status: false}. 

Also i deployed the resources and api as the guide suggested, and when i try hit the api gateway endpoint using postman i get the same 500, { status: false}. When i look on Xray to see whats wrong it says userId expected: S actual: NULL.

My guess is when i try postman the endpoint im not passing through the correct credentials. My header has a cognito-identity-id. In my authorisation i also have my aws access and secret key in it. 

Can't seem to figure out the problem.

**Comment by jayair** [comment]
Hmmm might be a good idea to ask the folks over on the serverless-offline repo?

**Comment by bharloe** [comment]
@Paul4912 since it is working with serverless invoke, and since you know it is hitting a dynamo db table of some sort, my best guess is that there is an issue with how you or postman forms the request. The easiest way to check if this is the case would be to adding logging to the get function to see if your params are set properly. In the get function on [line 15](https://github.com/AnomalyInnovations/serverless-stack-demo-api/blob/master/get.js#L15), try adding `console.log(params)` or something to that effect to see if the params are set as you would expect.
